### ISSUE TITLE
.cnt files

### ISSUE THREAD

**Issue by vishnu-ivariable** [ngebodh/GX_tES_EEG_Physio_Behavior#1]
Brother raw EEG data is in .cnt format and cant open through Python. It is throwing "'ascii' codec can't decode byte 0xa8 in position 0: ordinal not in range(128)" error.
![Screenshot (220)](https://github.com/ngebodh/GX_tES_EEG_Physio_Behavior/assets/105475692/b9dc7126-9737-43f8-ae7c-a9a9c2690793)
![Screenshot (221)](https://github.com/ngebodh/GX_tES_EEG_Physio_Behavior/assets/105475692/43924d4a-ab5b-4ec4-a39c-4a45d125d145)

**Comment by ngebodh** [comment]
Thanks for your feedback. 

There are known imcompatabilities with raw ANT .cnt files and MNE. 
There may be a fix coming soon from ANT. 
You can read more here:
https://github.com/mne-tools/mne-python/issues/3609

In the mean time there are a few options to use the data in MNE:
* You can use the [downsampled `.mat` versions](https://zenodo.org/record/4456079) of the files provided (see under "Extras"). These can be imported into Python then passed to MNE. 

* You can import the EEGlab `.set` files into MNE. These files are povided in BIDS format on [OpenNeuro here](https://openneuro.org/datasets/ds003670/versions/1.1.0). Here's a [Google Colab Notebook](https://colab.research.google.com/drive/1b0olN3BzqkeNtqPO31Hwx04EvksTLrOy?usp=sharing) showing how
